<?php 
    include('../components/header.php');
    include('../components/navbar.php');
    include('../components/infoEntreprise.php');
    include('../components/block_stages.php');
    include('../components/stagesEntreprise.php');
    include('../components/block_avis.php');
    include('../components/avisList.php');
    include('../components/footer.php');
?>